dataset_dir: "/workdir/datasets/Liquid3d" # path to the dataset directory with 'train' and 'valid' subdirs.
train_data:
  random_rotation: true # randomly rotate training data about the gravity axis.
data_dir: "/workdir/cconv/data/fluidmlp"
